// react-admin/src/containers/user/Login.js
/**
 *  author : bo.peng
 *  createTime 2018-10-26 20:03
 *  description :
 */
import React from 'react';
import {Form, Icon, Input, Button} from 'antd';
import { connect } from 'react-redux';
import user from "../../redux/actions";
import "./login.scss";
import Util from "../../Utils/Util";

const FormItem = Form.Item;

class Login extends React.Component {
	handleSubmit = (e) => {
		e.preventDefault();
		this.props.form.validateFields((err, values) => {
			if (!err) {
				console.log('Received values of form: ', values);
			}
			values.password = Util.pwdmd5(values.password);
			this.props.dispatch(user.login(values));
		});
	};

	render() {
		const {getFieldDecorator} = this.props.form;
		return (
			<div className="login-contrainer">
				<div className="login-form">
					<div className="title">CMS系统</div>
					<Form onSubmit={this.handleSubmit} className="content">
						<FormItem>
							{getFieldDecorator('userName', {
								rules: [{required: true, message: '请输入用户名!'}],
							})(
								<Input prefix={<Icon type="user" style={{color: 'rgba(0,0,0,.25)'}}/>}
								       placeholder="用户名"/>
							)}
						</FormItem>
						<FormItem>
							{getFieldDecorator('password', {
								rules: [{required: true, message: '请输入密码!'}],
							})(
								<Input prefix={<Icon type="lock" style={{color: 'rgba(0,0,0,.25)'}}/>} type="password"
								       placeholder="密码"/>
							)}
						</FormItem>
						<FormItem>
							<Button type="primary" htmlType="submit" className="login-form-button">
								登录
							</Button>
						</FormItem>
					</Form>
				</div>
			</div>
		);
	}
}
export default connect()(Form.create()(Login));

// kuaicto/oms-vue+typescript+antd/src/views/login/Login.vue
/**
*  author : bo.peng
*  createTime 2018-11-09 17:56
*  description : login
*/
<template>
    <article class="login">
        <div class="container">
            <header>
                logo
            </header>
            <article>
                <a-form @submit="handleSubmit" :autoFormCreate="(form)=>{this.form = form}">
                    <template v-if="form">
                        <a-form-item
                                :validateStatus="userNameError() ? 'error' : ''"
                                :help="userNameError() || ''"
                                fieldDecoratorId="userName"
                                :fieldDecoratorOptions="{rules: [{ required: true, message: 'Please input your username!' }]}"
                        >
                            <a-input placeholder='Username'>
                                <a-icon slot="prefix" type='user' style="color:rgba(0,0,0,.25)"/>
                            </a-input>
                        </a-form-item>
                        <a-form-item
                                :validateStatus="passwordError() ? 'error' : ''"
                                :help="passwordError() || ''"
                                fieldDecoratorId="password"
                                :fieldDecoratorOptions="{rules: [{ required: true, message: 'Please input your Password!' }]}"
                        >
                            <a-input type='password' placeholder='Password'>
                                <a-icon slot="prefix" type='lock' style="color:rgba(0,0,0,.25)"/>
                            </a-input>
                        </a-form-item>
                        <a-form-item>
                            <a-button
                                    type='primary'
                                    htmlType='submit'
                                    :disabled="hasErrors(form.getFieldsError())"
                            >
                                登录
                            </a-button>
                        </a-form-item>
                    </template>
                </a-form>
            </article>
        </div>
    </article>
</template>
<script lang="ts">
    import Login from "@/controller/login";

    export default Login;
</script>

<style scoped lang="less">
    .login {
        display: flex;
        height: 100%;
        justify-content: center;
        align-items: center;
        background:url("../../imags/bg.jpg");
        background-size: cover;
        .container {
            width: 400px;
            padding: 15px;
            background: #fff;
            border: 2px solid #ddd;
        }
    }
</style>
