// technical/src/views/global/Header.tsx
/**
 *  author : bo.peng
 *  createTime 2018-11-24 10:58
 *  description :
 */
import {Component, Vue, Watch} from 'vue-property-decorator';
import {Layout, Menu, Breadcrumb, Icon} from 'ant-design-vue';
import {routesConfig} from "@/router";

@Component
export default class Header extends Vue {
    public render() {
        return (<Layout.Header class="header">
            <div class="logo"/>
            <Menu
                theme="dark"
                class="menu"
                mode="horizontal"
                defaultSelectedKeys={['2']}
                style={{lineHeight: '64px'}}
            >
                {
                    routesConfig.routes[0].children.map( (item: any, i: number) => {
                        return <Menu.Item key={i}>{item.name}</Menu.Item>;
                    })
                }
            </Menu>
        </Layout.Header>);
    }
}

// react-admin/src/containers/global/Header.js
/**
 *  author : bo.peng
 *  createTime 2018-10-31 20:38
 *  description :
 */
import React from "react";
import {Layout,Dropdown,Menu, Icon} from "antd";
import {connect} from "react-redux";
import {action_currentUser} from "../../redux/actions";
import action_global from "../../redux/actions/global";
const { Header } = Layout;
class HeaderTop extends React.Component{
	constructor(props){
		super(props);
		this.exit= this.exit.bind(this);
	}
	componentDidMount(){
		this.props.dispatch(action_global.permission.menu.request("menu"));
	}
	update(){
	}
	exit(){
		this.props.dispatch(action_currentUser.exit.request(this.props.currentUser));
	};
	showChildren(item){
		this.props.dispatch(action_global.permission.menuChidren(item));
	}
	render(){
		return (
			<Header className="header">
				<div className="logo">SUDAO-OMS</div>
				<Dropdown overlay={
					<Menu>
						<Menu.Item onClick={this.update}>修改密码</Menu.Item>
						<Menu.Item onClick={this.exit}>退出</Menu.Item>
					</Menu>
				}
				          className="top-silder">
			<span className="ant-dropdown-link">
				{this.props.currentUser.data.userName} <Icon type="down" />
			</span>
				</Dropdown>
				<Menu
					theme="dark"
					mode="horizontal"
					defaultSelectedKeys={['0']}
					style={{lineHeight: '64px'}}
				>
					{
						this.props.menu.data && this.props.menu.data.menus.map((item,i)=>
							<Menu.Item onClick={this.showChildren.bind(this,item)} key={i}>{item.name}</Menu.Item>
						)
					}
				</Menu>
			</Header>
		);
	}
}
export default connect(state=>state.global.permission)(HeaderTop);
