// technical/src/views/Container.tsx
/**
 *  author : bo.peng
 *  createTime 2018-11-23 13:05
 *  description : 盒子
 */
import {Component, Vue, Watch} from 'vue-property-decorator';
import {Layout, Menu, Icon} from 'ant-design-vue';
import Header from './global/Header';
import LeftMenu from './global/LeftMenu';

const {Content, Footer} = Layout;

@Component
export default class Container extends Vue {
    public render() {
        return (<article class="main">
            <Layout>
                <Header>header</Header>
                <Layout>
                    <LeftMenu/>
                    <Layout>
                        <Content>
                            <router-view/>
                        </Content>
                        <Footer>footer</Footer>
                    </Layout>
                </Layout>
            </Layout>
        </article>);
    }
}

// react-admin/src/containers/Container.js
/**
 *  author : bo.peng
 *  createTime 2018-10-26 14:58
 *  description :
 */
import React from "react";
import {Layout} from 'antd';
import Header from "./global/Header";
import SiderMenu from "./global/SiderMenu.js";
import connect from "react-redux/es/connect/connect";
import {RouteChildren} from "../router";

const { Content, Sider, Footer} = Layout;

function Container(props){
	return (
		<Layout>
			<Header {...props}/>
			<Layout>
				<Sider width={200}>
					<SiderMenu/>
				</Sider>
				<Layout>
					<Content style={{padding: 0, margin:0}}>
						<RouteChildren {...props}/>
					</Content>
				</Layout>
			</Layout>
			<Footer style={{ textAlign: 'center' }}>
				Ant Design ©2018 Created by Ant UED
			</Footer>
		</Layout>
	)
}
export default connect(
	state=>{
		return {currentUser:state.currentUser}
	},
)(Container);
